### ISSUE TITLE
Typo in href causes link to fail and missing/wrong doc page linked

### ISSUE THREAD

**Issue by vitorinoaraujo** [codenvy/che-site#1]
The problem is in the "Plug-Ins" section of the page (right above the footer, ).

There is a missing **=** sign in line number 208 in the href attribute causes the link to doc page to fail

````html
Che <a href"https://eclipse-che.readme.io/docs/plug-ins">includes a rich set</a> of plug-ins. You can also <a href="https://eclipse-che.readme.io/docs/getting-started">create and package</a> your own.
````

Also, the link for **https://eclipse-che.readme.io/docs/getting-started** returns a 404

**Comment by TylerJewell** [comment]
Hi - yes confirmed.  This has been fixed with an update.  Thanks for taking the time to report this.
